// Generated by https://quicktype.io

export interface BotConfig {
    botSettings: BotSettings
    images: Images
    itemArrayLink: string
    caliberArrayLink: string
}

export interface BotSettings {
    color: [number, number, number]
    altColor: [number, number, number]
    errorColor: [number, number, number]
}

export interface Images {
    logo250: string
    secondBanner: string
    slashBanner: string
    author: string
    thumbnails: { [key: string]: string }
}
